### ISSUE TITLE
Lookup enhancements

### ISSUE THREAD

**Issue by anon5r** [anon5r/skytools#11]
# Overview

The Lookup function retrieves not only the DID reference but also its account details.

# Purpose

It would be nice to be able to get and view account details for that repository, not just the ID reference.

**Comment by anon5r** [comment]
Display the details, posts, follows and likes etc... the target ID using AT Protocol.

**Comment by anon5r** [comment]
These are limited to information that can be obtained without logging into [bsky.social](https://bsky.social). So, only information published via the AT Protocol.

This allows only partially restricted information to be retrieved.

Specifically, it does not seem to be able to acquire data such as followers.

**Comment by anon5r** [comment]
# TODO (Next task)

- [ ] Show quoted post inline
- [ ] Get the rest of the list
- [ ] Get user-generated feeds
- [ ] Integration with Identity history
